language: go
sudo: required

go:
  - 1.6
  - 1.7

services:
  - docker

install:
  # pull required dependencies
  - make dependencies

script:
  # statically compile
  - make stat

after_success:
  # clean, build, push to docker
  - make clean
  - make fulldocker
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag unixvoid/bitnuke unixvoid/bitnuke
  - docker push unixvoid/bitnuke
  # push binaries to binder
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/bitnuke*` --form path=bitnuke/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/bitnuke*` --form filename=bitnuke-latest-linux-amd64 --form path=bitnuke/ https://cryo.unixvoid.com/upload
